# Database - dev specific
spring.datasource.url=jdbc:mysql://localhost:3306/study?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=ca15b7207c65bde943b242e59124cc2c280cb9d293fc4677a9511fcafaefb672
spring.datasource.password=ca15b7207c65bde943b242e59124cc2c280cb9d293fc4677a9511fcafaefb672
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
spring.jpa.show-sql= true
spring.jpa.generate-ddl=true

# JWT - dev secret (weaker is OK for dev)
spring.jwt.secret=shawksSecretKeyThatShouldBeLongEnoughForHS256Algorithm

# Email - dev credentials
spring.mail.username=chaouki.neily@etudiant-fst.utm.tn
spring.mail.password=pbpwfuwjirqjaeih
spring.mail.properties.mail.debug=true

# Verification URL - dev
app.verification-url=http://localhost:8080/auth/verify
