spring.application.name=JwtAuth
spring.profiles.active=dev
#the prefix configserver has nothing to do with the fact that config server we use is actually named configserver
spring.config.import=optional:configserver:http://localhost:8060/

# 4. Optional: Config Server connection settings
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=4
# making the actuator restart the MS whenthere is a change to the property file in config server
management.endpoints.web.exposure.include=*
encrypt.key=${ENCRYPT_KEY}
#now if we add a diffrent config to the gconfig server in git we need to restart via actuator , but that could lead to to hundreds of microservices
#restarting , to fix that we use spring cloud bus that connect to a event framewrok like rabbit MQ and this makes it so that
#only one instance of the microservices in contacted and rabbit MQ communicaates the changes to the other microservices on its own
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
#guest is the defautl value
#rabbit mq can start on docker with this command
## latest RabbitMQ 4.x
#docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4-management
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
