spring.application.name=configServer
server.port=8060
#native profile for config server is  = class path , meaning saving the configs in class path
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config/
