spring.application.name=configServer
server.port=8060
#native profile for config server is  = class path , meaning saving the configs in class path
#this approach is for dev only , best practice is via github
#spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=classpath:/config/
#storing property folders in github
spring.profiles.active=git
spring.cloud.config.server.git.uri=https://github.com/chawky/configServer.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.timeout=5
spring.cloud.config.server.git.clone-on-start=true
#this is used to always get the properties from git and override the one locally
spring.cloud.config.server.git.force-pull=true
#authertication using goit key
#Option 2: Use Personal Access Token (Recommended)
#Create token:
#GitHub ? Settings ? Developer settings ? Personal access tokens ? Tokens (classic)
#Generate new token with repo permissions
#Copy the token
spring.cloud.config.server.git.username=chawky
spring.cloud.config.server.git.password=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
#now we need to encrypt the sensitive details
encrypt.key=a8f5f167f44f4964e6c998dee827110c8bd4e48b41c12c8b65b8b8e8e8e8e8e81
