spring.application.name=JwtAuth
spring.profiles.active=dev
#the prefix configserver has nothing to do with the fact that config server we use is actually named configserver
spring.config.import=optional:configserver:http://localhost:8060/

# 4. Optional: Config Server connection settings
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=4
